/* Curated usage chapters. Registry data is generated separately. */
window.HYPERBENCH_PAGES = [
  {
    id: "overview",
    title: "概览与范围",
    eyebrow: "01 / OVERVIEW",
    html: '<h2>一个可审计的 solver benchmark</h2><p class="lead">用相同的问题定义、初态和参考解，比较不同数值方法；把算法精度、实现耗时与理论计算成本分开报告。</p><div class="flow"><div>定义问题<small>PDE · 初态 · 参数 · horizon</small></div><div>冻结协议<small>solver · 网格 · 参考解</small></div><div>独立评测<small>误差 · 重复计时 · 覆盖率</small></div><div>生成报告<small>曲线 · Pareto · 可复核产物</small></div></div><p>新增独立的 <code>complex</code> suite，按解析、半解析、数值三个 tier 分类；<a href="#reference-tiers">查看准入规则与用法</a>。旧 suite 定义不变。</p><h3>先区分不同覆盖范围</h3><div class="grid"><div class="tile"><h3>Compact v2</h3><p>12 个方程族、48 个固定场景。37 个解析/半解析参考，9 个通过经验门槛的数值参考，2 个暂定挑战场景。</p></div><div class="tile"><h3>扩展精度与效率评测</h3><p>增加 6 个 Burgers stress 场景。默认 Burgers 评测选择 5 个基础 + 6 个 stress 场景，统一输出 10 个时刻。</p></div><div class="tile"><h3>Burgers solver 目录</h3><p>61 个明确配置，包括 51 个通量/重构/RK 组合与 10 个独立实现。不是所有数学算法的穷举。</p></div><div class="tile"><h3>规范计算模型</h3><p>当前映射其中 52 个实现，按规范计算图与实际步数计成本；其余 9 个明确排除，不当作零成本。</p></div></div><div class="note">场景“支持规划”不表示每个 solver × 参数 × 网格都完成了实验。完整覆盖、失败状态与参考质量必须结合具体报告阅读。</div><h3>从哪里开始</h3><p>首次使用：阅读<a href="#quickstart">快速开始</a>。接入自己的算法：阅读<a href="#solver">Solver 接口</a>。解读报告：阅读<a href="#metrics">精度与效率</a>和<a href="#cost">计算模型</a>。</p><p>代码仓库目前为私有；此网站公开使用文档，不提供公开源码下载。已有仓库权限的用户可按示例运行。</p>',
  },
  {
    id: "quickstart",
    title: "快速开始",
    eyebrow: "02 / DOCUMENTATION",
    html: '<h2>先规划，再执行</h2><p class="lead">几个 Python 调用完成评测与报告生成。正式运行前冻结代码和协议，是可复现流程的一部分。</p><h3>1. 环境与仓库</h3><p>当前支持 macOS/Linux 的 CPU 评测。使用 Python 3.12 已验证环境；NumPy、SciPy、Matplotlib 等版本由 requirements 固定。Classic/SharpClaw 还需要可用的 Fortran/C 编译环境；HLLD wrapper 需要 C 编译器。</p><pre data-lang="BASH"><code># 需要私有代码仓库的访问权限\ngit clone git@github.com:NOrangeeroli/meta-pde-solver.git\ncd meta-pde-solver\npython3.12 -m venv .venv\nsource .venv/bin/activate\npython -m pip install -r hyperbench/requirements.txt</code></pre><p>依赖安装可能需要平台相关的原生编译器配置。Euler 参考等上游资源的获取方式见代码仓库的 <code>fetch_sources.py</code> 与开发指南；这些不是 PyPI 上名为 hyperbench 的安装包。</p><h3>2. 选择 solver 和网格</h3><pre data-lang="PYTHON"><code>from hyperbench import Benchmark\n\nbench = Benchmark(\n    equation=&quot;burgers&quot;,\n    solvers=[&quot;classic_mc&quot;, &quot;sharp_weno5&quot;, &quot;wz_llf&quot;],\n    grids=[40, 80, 160],\n)\nprint(len(bench.protocol[&quot;jobs&quot;]))  # 99 = 11 scenes × 3 solvers × 3 grids\nbench.prepare(&quot;experiments/hyperbolic/my_burgers_v001&quot;)</code></pre><p><code>prepare()</code> 只写 config.json 和 README，不运行 PDE。补充目标、假设和检查门槛后，将本次代码、配置、README 提交并推送。正式执行要求整个 checkout 干净、当前 HEAD 已在远端；不要把无关的未完成修改一并提交。</p><h3>3. 执行与查看报告</h3><pre data-lang="PYTHON"><code>from hyperbench import Benchmark\n\nreport = Benchmark.load(&quot;experiments/hyperbolic/my_burgers_v001&quot;).run()\nprint(report.html)       # 离线、自包含 HTML 的绝对路径\nprint(report.summary)    # 成功 / 失败 / 覆盖状态\nreport.validate()        # 独立重算误差并核对校验和</code></pre><div class="note">不要覆盖完成的实验。再次测量使用新目录；完成后更新实验 README 的结果、局限和决策，再提交并推送结果。报告生成成功不等于所有 solver 都成功。</div><h3>常用参数</h3><div class="table-wrap"><table><thead><tr><th>参数</th><th>默认值</th><th>行为</th></tr></thead><tbody><tr><td>equation</td><td>burgers</td><td>选择 Case.equation</td></tr><tr><td>solvers</td><td>None</td><td>使用所选场景的内置候选；也接受 Solver 对象</td></tr><tr><td>grids</td><td>32, 64, 128</td><td>每轴单元数，整数 ≥ 8；二维 N 表示 N² 个单元</td></tr><tr><td>cases</td><td>None</td><td>该方程在 suite 中的全部场景；显式子集标记 SUBSET</td></tr><tr><td>suite_name</td><td>extended</td><td>compact / extended / complex / burgers-stress / burgers-validation</td></tr><tr><td>warmups / repeats</td><td>2 / 7</td><td>首次调用另计；预热整数 ≥ 1，正式重复整数 ≥ 3</td></tr><tr><td>timeout_seconds</td><td>600</td><td>整个 worker 的正有限超时时间，单位秒</td></tr><tr><td>reference_manifest</td><td>None</td><td>complex 使用内置固定数值 GT；其他数值场景须提供匹配的 reference_manifest</td></tr></tbody></table></div>',
  },
  {
    id: "architecture",
    title: "结构与模块",
    eyebrow: "03 / DOCUMENTATION",
    html: '<h2>从 Case 到 Report</h2><p class="lead">规划、数值求解、参考解与报告各自有明确职责。用户代码不需要调用内部 worker。</p><div class="flow"><div>Benchmark<small>选场景、方法、分辨率</small></div><div>plan / prepare<small>协议与公共输入</small></div><div>worker<small>独立进程推进 PDE</small></div><div>audit / Report<small>重算、汇总与可视化</small></div></div><h3>模块分工</h3><div class="table-wrap"><table><thead><tr><th>层</th><th>模块</th><th>职责</th></tr></thead><tbody><tr><td>公共接口</td><td>api · user_solver</td><td>Benchmark / Solver / Report；用户函数解析与输入副本</td></tr><tr><td>问题定义</td><td>schema · v2_catalog · burgers_stress · complex_suite · problems</td><td>Case、固定初态/参数、cell-average 初始化</td></tr><tr><td>真实 solver</td><td>solver_registry · claw · advanced_claw · fv · advanced_fv · spectral</td><td>方程相关分派；Clawpack、本地 FV、Fourier 方法</td></tr><tr><td>Burgers 组合</td><td>burgers_combinations · example_solver</td><td>61 个目录配置与独立 WENO3 示例</td></tr><tr><td>参考解</td><td>exact · v2_exact · complex_exact · complex_gt · gt_study</td><td>解析/半解析参考、数值 GT 选择与验证</td></tr><tr><td>CPU 评测</td><td>efficiency · efficiency_run</td><td>计划、线程环境、逐配置隔离计时、失败保留</td></tr><tr><td>报告</td><td>efficiency_report · report_views · pareto_views · presentation</td><td>只读审计、场景等权聚合、前沿与新版本导出</td></tr><tr><td>理论成本</td><td>cost_graph · cost_kernels · cost_model · cost_report</td><td>标量 DAG、规范 kernel、动态计数、成本与误差配对</td></tr><tr><td>复用与维护</td><td>reuse · doccheck</td><td>冻结数据复用、模块文档完整性和索引检查</td></tr></tbody></table></div><h3>三个入口，三种用途</h3><ul><li><code>Benchmark</code>：当前精度 + CPU 效率接口，统一 10 个输出时刻。</li><li><code>v2_run</code>：compact v2 发布流程，使用目录本身定义的 horizon。</li><li><code>run</code>、<code>sweep</code> 等：历史协议复现。其结果 schema 不能与新 API 混用。</li></ul><h3>数组契约</h3><pre data-lang="ARRAY SHAPES"><code>initial:    (C, N)       # 1D cell averages\ntrajectory: (10, C, N)   # API 的 10 个输出时刻\n\ninitial:    (C, N, N)       # 2D\ntrajectory: (10, C, N, N)</code></pre><p>所有方法共享同一初态定义和输出时刻。参考解在计时外准备，solver 只收到初态和问题描述。参考解降采样使用守恒的块平均，而不是取某个点。</p><div class="note">导入包不会自动运行求解器或下载数据。报告 writer 会写文件，validate 才是只读操作；历史 writer 的副作用应按各模块说明确认。</div>',
  },
  {
    id: "cases",
    title: "方程、初态与 GT",
    eyebrow: "04 / DOCUMENTATION",
    html: '<h2>固定问题，明确参考</h2><p class="lead">场景目录由代码导出，包含方程、初态、边界、参数、原始 horizon 和参考类型。目录覆盖不等于完整实验覆盖。</p><h3>参考构造与资格状态</h3><div class="table-wrap"><table><thead><tr><th>类型</th><th>例子与构造</th><th>解释边界</th></tr></thead><tbody><tr><td>解析 / 半解析</td><td>平移、Riemann 解、Burgers 熵解与 Hopf–Lax 势函数差</td><td>求根、求积或搜索可能有数值误差；半解析不等于严格精确</td></tr><tr><td>qualified 数值参考</td><td>细网格、空间收缩、半 CFL、不同 solver 交叉检查</td><td>经验门槛，不是严格误差上界</td></tr><tr><td>provisional 数值参考</td><td>未满足全部资格要求的挑战场景</td><td>保留展示，但不进入正式 Pareto 前沿</td></tr></tbody></table></div><p>历史 compact 数值 GT 门槛包括空间差 ≤ 1%、时间步差 ≤ 0.2%、空间收缩比 ≤ 0.9，与至少另一个有效候选差 ≤ 1%。符合门槛仍不能支持小于参考不确定性尺度的精细排名。</p><h3>Horizon 的两种含义</h3><p>下方目录显示 compact/stress 原始时间序列。精度/效率 API 保留每场景最大 T，替换为 <code>t/T = 0.1, 0.2, …, 1.0</code>。时间误差的 mean/median/max 都在这 10 个时刻计算；不是多次从头运行到 10 个不同 horizon。</p><h3>场景目录：54 个历史场景 + 60 个复杂场景</h3><p>点击方程族展开；每条记录注明 suite 和 reference tier。旧 suite 的网格可显式覆盖，complex 仅允许已验证网格。literature 开发验证场景不在这份正式目录内。</p><div id="case-catalogue"></div><h3>Burgers 扩展初态</h3><p>额外覆盖 smooth_shock、box、multishock、ood_highfreq、ood_collision、ood_rarefaction。它们复用旧 solver-learning 的固定初态，但不声称复用了旧 CFL 或同一 GT。默认最终 T = 0.6。</p>',
  },
  {
    id: "solver",
    title: "接入与选择 solver",
    eyebrow: "05 / DOCUMENTATION",
    html: '<h2>只实现推进函数</h2><p class="lead">用户 solver 和内置 solver 经过相同的精度、计时和有效性检查。</p><h3>放到可导入的 Python 模块</h3><pre data-lang="PYTHON"><code># my_solver.py — 最小可运行适配示例\nfrom hyperbench.solvers.example_solver import solve as weno3\n\ndef solve(problem):\n    # 实际接入时，在这里替换为自己的时间推进。\n    return weno3(problem)</code></pre><pre data-lang="PYTHON"><code>from hyperbench import Benchmark, Solver\n\nbench = Benchmark(\n    &quot;burgers&quot;,\n    solvers=[&quot;classic_mc&quot;, Solver(&quot;mine&quot;, &quot;my_solver:solve&quot;)],\n    grids=[40, 80, 160],\n)\nbench.prepare(&quot;experiments/hyperbolic/my_solver_v001&quot;)\n# 冻结、提交并推送后：\nreport = Benchmark.load(&quot;experiments/hyperbolic/my_solver_v001&quot;).run()</code></pre><div class="table-wrap"><table><thead><tr><th>输入字段</th><th>含义</th></tr></thead><tbody><tr><td>problem.initial</td><td>float64 cell averages；独立可写副本</td></tr><tr><td>problem.auxiliary</td><td>介质或地形的数组字典；独立副本</td></tr><tr><td>problem.times</td><td>从 t=0 起算的物理时刻，不是步长</td></tr><tr><td>problem.dx</td><td>每轴间距 tuple，一维使用 dx[0]</td></tr><tr><td>problem.case</td><td>方程、参数、边界和初态定义</td></tr><tr><td>problem.n</td><td>每轴单元数</td></tr></tbody></table></div><h3>返回值</h3><pre data-lang="PYTHON"><code>return trajectory\n# 或\nreturn trajectory, {&quot;steps&quot;: number_of_steps}</code></pre><p>trajectory 是 float64 NumPy 数组，Burgers 形状为 <code>(10, 1, N)</code>；不包含额外的 t=0 帧。metadata 必须可 JSON 序列化。每次调用从初态独立开始，不可读取 GT 生成输出。</p><p>名称不能覆盖内置名称；入口是顶层函数或 <code>module:function</code> 字符串。lambda、局部函数、notebook 中的 __main__ 函数不能作为隔离 worker 的入口。其他方程通过 <code>equations=("euler",)</code> 等显式声明。</p><h3>61 个 Burgers 配置如何组成</h3><div class="table-wrap"><table><thead><tr><th>部件</th><th>选择</th></tr></thead><tbody><tr><td>通量</td><td>Godunov、局部 Lax–Friedrichs/Rusanov、Engquist–Osher</td></tr><tr><td>重构</td><td>PC、minmod、MC、van Leer、superbee、WENO3-JS、WENO5-JS、WENO5-Z</td></tr><tr><td>时间推进</td><td>SSPRK2 / SSPRK3；PC 另有 Euler</td></tr><tr><td>组合数</td><td>3 × 8 × 2 + 3 = 51；另有 10 个独立配置</td></tr></tbody></table></div><p>组合方法统一 CFL=0.35，按阶段速度拒绝并缩小时间步。命名例如 <code>fv_godunov_weno5z_rk3</code>。独立 Classic/SharpClaw 等保留自己的推进设置。Classic MC 的波限制器与 MUSCL MC 双迹重构不能简单视为相同实现。</p><pre data-lang="PYTHON"><code>from hyperbench.burgers_combinations import catalogue\nbench = Benchmark(&quot;burgers&quot;, solvers=catalogue(), grids=[40, 80, 160])</code></pre><div class="note">WENO5 + RK2 不代表整体五阶。此目录是已实现配置的穷举，不包含所有 ENO、DG、PPM、谱黏性或隐式方案。</div>',
  },
  {
    id: "metrics",
    title: "精度、效率与 Pareto",
    eyebrow: "06 / DOCUMENTATION",
    html: '<h2>报告中的数字怎么算</h2><p class="lead">先在场景内汇总，再对场景等权平均。性能数字必须连同计时范围和覆盖率解读。</p><h3>误差</h3><pre data-lang="METRIC DEFINITION"><code>e(t) = max over components [ MAE(q(t), reference(t))\n                            / max(RMS(reference(t)), 0.1) ]\n\nscene_mean   = mean(e(t₁), …, e(t₁₀))\nscene_median = median(e(t₁), …, e(t₁₀))\nscene_max    = max(e(t₁), …, e(t₁₀))\n\nfamily_metric = arithmetic mean of scene_metric</code></pre><p><code>time_max</code> 是“场景内最大误差”的场景平均。<code>worst_scene_time</code> 另记所有场景与快照中的最大值。均匀采样的平均不是梯形时间积分，有限快照也不能保证捕获全程峰值。</p><h3>CPU 计时边界</h3><div class="table-wrap"><table><thead><tr><th>包含</th><th>不包含</th></tr></thead><tbody><tr><td>初态副本、solver 设置、工作数组分配、完整 rollout 与输出快照</td><td>进程启动、顶层 import、entrypoint 解析、GT、误差计算、磁盘输出</td></tr><tr><td>solver 内发生的懒加载计入对应调用</td><td>不能把首次调用当作完整进程冷启动</td></tr><tr><td>一次首次调用 + 默认 2 次预热 + 7 次正式重复</td><td>预热和首次调用不混入正式中位数</td></tr></tbody></table></div><p>CPU 单线程、float64、batch=1；每配置独立 worker，parent 串行运行。图上 x 是“各场景重复计时中位数”的平均；误差棒为场景四分位数的平均，不是置信区间。峰值 RSS 属于整个 worker，不是 solver 独占内存。</p><h3>前沿与失败</h3><p>当没有其他点在两轴都不差且至少一轴严格更好时，该点属于经验 Pareto 前沿。左下方更好；灰色阴影是被支配区域。连线只连接同一 solver 的已有网格点，不代表中间分辨率已测量。</p><ul><li>同一 solver × 网格须覆盖该组全部选中场景且有效，才有聚合点。</li><li>不支持、超时、异常、无效和不可重复结果保留在 coverage，不静默删除。</li><li>暂定参考不进入前沿；子集显示 SUBSET。</li><li>不同通量子图的阴影在各自比较范围内重新计算。</li></ul><div class="note">NumPy、Fortran、不同优化程度都会影响实测耗时。相近算法的墙钟差异不等于纯算法加速比；理论成本见下一章。</div>',
  },
  {
    id: "cost",
    title: "Computation model",
    eyebrow: "07 / DOCUMENTATION",
    html: '<h2>统一计算图，不模拟某台机器</h2><p class="lead">规范数值 kernel + 实际 rollout 计数 + 抽象资源评分。CPU 实测耗时单独保留。</p><h3>第一层：计算图</h3><p>float64 标量 DAG 分别统计加减乘除、abs、比较、select、sign、finite 和 AND。纯常量折叠与 kernel 内结构性公共子表达式合并（CSE）开启；不做 FMA、结合律重排或跨 kernel 融合。select 两侧均求值。</p><p>每次 RHS 按 N+2 个单元的双迹、N+1 个面通量、N 个 divergence 计数。PC 直接别名输入；时间步和 RK stage 串行，kernel 内单元并行。</p><h3>第二层：实际执行次数</h3><pre data-lang="ROLLOUT COUNTERS"><code>RHS calls = rk × accepted_steps + (rk − 1) × rejected_steps\nstage updates = rk × (accepted_steps + rejected_steps)</code></pre><p>modular FV 拒绝重试时复用首次 RHS。计数从原结果 metadata 读取，要求多次重复一致；不会把预热/计时重复乘入单轨迹成本。</p><h3>第三层：资源评分</h3><pre data-lang="ABSTRACT MACHINE"><code>W = sum(operation_count[j] × weight[j])\nD = barrier_span\nQ = policy_bytes\n\nvirtual_ticks = max(W / lanes, D, Q / bytes_per_tick)</code></pre><div class="table-wrap"><table><thead><tr><th>参数</th><th>默认</th><th>含义</th></tr></thead><tbody><tr><td>unit</td><td>所有操作权重 1</td><td>统一原语工作量；比较与选择不是 FLOPs</td></tr><tr><td>division8</td><td>除法为 8，其余为 1</td><td>任意指定的敏感性 profile，不是硬件标定</td></tr><tr><td>lanes</td><td>8</td><td>每 tick 理想工作容量，不是 CPU 核数或 CUDA 线程数</td></tr><tr><td>带宽</td><td>64 bytes/tick</td><td>虚拟容量；tick 没有换算成秒</td></tr><tr><td>快存</td><td>32 KiB</td><td>整个工作区的单一容量门槛，不模拟 cache 层级</td></tr></tbody></table></div><h3>它更像 GPU 还是 CPU？</h3><p><strong>两者都不是。</strong>结构适合数据并行，CPU SIMD/多线程和 GPU SIMT 都可实现。但模型没有 CPU 执行端口/缓存层级，也没有 GPU warp/block/SM 调度、occupancy、启动开销或主机–设备传输。增大 lanes 并不等于模拟 GPU。</p><h3>内存政策与局限</h3><p><code>logical_bytes</code> 按物化 kernel 的读写计数；相邻单元不共享读取。工作区可完全放入快存时，<code>policy_bytes</code> 仅计初态读取和快照写出；否则使用逻辑流量。这不是实测 DRAM 流量或最小 I/O 下界。</p><p>整个 rollout 先累计再取 max，可能过度理想化不同阶段的重叠。同一操作权重同时用于 work 和 span，而真实吞吐与依赖延迟不同。循环/CFL 标量控制、边界寻址与复制、分配和 I/O 未计入数值 kernel 工作量。</p><pre data-lang="PYTHON"><code>from hyperbench.cost_model import analyze, virtual_score\n\n# 计数仅作接口示例；实际报告使用 solver 记录。\ncost = analyze(\n    &quot;fv_llf_mc_rk3&quot;, n=160,\n    metadata=[{&quot;steps&quot;: 200, &quot;rejected_steps&quot;: 0}],\n    profile=&quot;division8&quot;, fast_memory_bytes=32768,\n)\nprint(cost[&quot;operations&quot;])\nprint(cost[&quot;weighted_work&quot;], cost[&quot;barrier_span&quot;])\nprint(virtual_score(cost))  # 虚拟 ticks，不是秒</code></pre><p>当前映射 51 个 modular FV 配置与 custom_weno3，共 52/61。原生 Classic 五个、SharpClaw 两个、旧 fv_mc 与 wz_llf 未建立可靠图/动态计数映射，明确排除。</p><div class="note">已有 v031 数据在默认机器下全部由 W/8 主导，因此虚拟前沿和 division8 相同。这批结果尚未验证内存项、并行深度项或真实 CPU/GPU 秒数预测能力。</div><p><a href="cost-model.md">阅读完整模型文档（Markdown）</a></p>',
  },
  {
    id: "reports",
    title: "结果与报告文件",
    eyebrow: "08 / DOCUMENTATION",
    html: '<h2>从结果追溯到原始记录</h2><p class="lead">HTML 用于阅读，JSON/CSV 用于分析，manifest 用于核验。未通过的配置也属于报告的一部分。</p><div class="table-wrap"><table><thead><tr><th>产物</th><th>内容</th></tr></thead><tbody><tr><td>report.html</td><td>自包含离线 HTML，嵌入图与结果表</td></tr><tr><td>points.json / csv</td><td>solver × 网格 × 场景组聚合指标</td></tr><tr><td>scene_metrics.csv</td><td>每场景误差统计、计时、首次调用与 RSS</td></tr><tr><td>snapshot_metrics.csv</td><td>每时刻/分量的空间误差</td></tr><tr><td>coverage.csv / summary.json</td><td>状态、覆盖率、成功与失败</td></tr><tr><td>inputs / runs</td><td>冻结输入、参考解、轨迹、计时、metadata 和日志</td></tr><tr><td>provenance.json / manifest.json</td><td>代码版本、环境、路径、字节数与 SHA256</td></tr></tbody></table></div><h3>已归档的 Burgers 对比</h3><p>v029 共 3,289 条场景/solver/网格记录；其中 3,187 条复用已审计测量、102 条定向新增。未对所有 solver 无差别加密网格。</p><p>v031 从中选取已建模的 52 个实现：2,574 条轨迹；每个场景视图 234 个 solver × 网格点。没有重新调用 PDE solver。</p><figure><a href="assets/burgers-cost.png"><img src="assets/burgers-cost.png" width="2850" height="2400" loading="lazy" alt="Burgers 11 场景上的成本与误差对比，四列分别为单位工作量、除法加权、虚拟 ticks 和实测秒数，三行为时间 mean、median、max。"></a><figcaption>来源：冻结实验 v031。点击查看大图。每种颜色为一个 solver，连线连接不同网格；灰色表示被支配区域。</figcaption></figure><h3>全 11 场景 · 平均误差</h3><div class="table-wrap"><table><thead><tr><th>成本横轴</th><th>经验前沿点数</th></tr></thead><tbody><tr><td>单位运算成本</td><td>31</td></tr><tr><td>division8 加权成本</td><td>29</td></tr><tr><td>虚拟 ticks</td><td>29</td></tr><tr><td>同一子集的实测耗时</td><td>24</td></tr></tbody></table></div><p>单位模型与真机前沿共有 18 个点。排名取决于成本假设和实现后端；这些数字不构成真实用时预测模型的验证。</p><h3>仅更新展示，不重跑 solver</h3><p>普通 CPU 报告使用 <code>report.export(new_directory)</code>，需先创建并冻结新导出目录的 README。计算模型报告另建含 <code>{"source": "源实验路径"}</code> 的 config.json 与 README，再运行：</p><pre data-lang="BASH"><code>python -m hyperbench.cost_report --destination experiments/hyperbolic/NEW_COST_ID\npython -m hyperbench.cost_report --destination experiments/hyperbolic/NEW_COST_ID --validate</code></pre><p>成本报告额外输出 scene_costs、coverage、frontiers、序列化 kernels 与 model_spec。CLI config 当前只接受 source，不接受未实现的硬件 profile 覆盖字段。</p>',
  },
  {
    id: "reproducibility",
    title: "复现与维护",
    eyebrow: "09 / DOCUMENTATION",
    html: '<h2>把实验作为有版本的交付物</h2><h3>代码模块结构</h3><p>hyperbench 根目录保留公开 API 与数据契约。equations 按 13 个物理方程目录组织，每个目录包含 equation.py（物理契约）、scenarios.py（场景参数）、initial.py（初态材料）、references.py（连续参考）。共用数学在 equations/_shared；cases 只选择套件和检查准入。solvers（共用数值方法）、evaluation（评测）、reporting（报告）、computation（计算模型）、validation（资格验证）、legacy（历史流程）及 maintenance（维护）继续按职责共享。旧模块路径集中在 _compat 中兼容，已有脚本无需立即改写。</p><p class="lead">可追溯的代码、协议与数据，是比较 solver 的前提。</p><ol><li>新建 <code>experiments/&lt;topic&gt;/&lt;new-id&gt;/</code>，记录目标、假设、门槛和命令。</li><li>运行前将代码、配置、协议提交并推送；保持 checkout 干净。</li><li>记录完整 pre-run SHA、环境、参考来源与原始结果。</li><li>保留失败；独立重算指标、核对 SHA256。</li><li>补齐结果、分析、局限和决策，再提交推送。修订实验使用新 ID。</li></ol><h3>哪些成本不能混用</h3><p>真实 wall time 依赖主机与后端，规范计算模型依赖图与资源假设。训练成本和 GPU 异步计时不在当前 CPU 协议内。比较新 solver 时必须同时核对场景、网格、T、参考解、输出帧与计时范围。</p><h3>节制地扩展前沿</h3><p><code>method_tiers</code> 为每个方法指定网格 tier 子集；候选应来自已有总体/分组前沿。每个保留的方法/网格仍覆盖所有选中场景。<code>reuse_sources</code> 只复用经过核验的不可变成功记录，保存原计时，不缩放。</p><h3>日常检查</h3><pre data-lang="BASH"><code>ruff check --config hyperbench/ruff.toml hyperbench tests/hyperbench\nruff format --check --config hyperbench/ruff.toml hyperbench tests/hyperbench\npython -m hyperbench.doccheck\npython -m unittest discover -s tests/hyperbench -q</code></pre><p>测试需安装科学与原生依赖。不要用 <code>python -O</code> 跑审计；部分历史断言依赖 assert。<code>cleanup_check</code> 是固定旧基线的一次性结构审查，不是当前日常门槛。</p><h3>文件路径与可移植性</h3><p>自包含 HTML 可以直接分享，但整套原始实验不一定可随意移动。部分早期 manifest 含旧 worktree 绝对路径；迁移核验须明确记录根目录映射，继续比对原始字节数/哈希，不篡改冻结 manifest。</p><h3>本网站的版本</h3><p>此文档以 2026-09-22 审查后的行为为依据；场景目录从代码生成。网站发布与科学运行分开，不因发布网页重新计算或改写冻结实验。公开仓库仅保存网页文档与选定结果图；核心源码仓库仍为私有。</p>',
  },

  {
    id: "reference-tiers", title: "参考解与复杂场景", eyebrow: "REFERENCE TIERS",
    html: '<h2>解析、半解析与数值参考</h2><p class="lead">复杂性可以增加，但参考解的适用条件与误差证据必须明确。</p><table><thead><tr><th>Tier</th><th>构造</th><th>complex 场景数</th></tr></thead><tbody><tr><td>1 · analytic</td><td>显式连续解或有限的精确波路径；单元积分仍需检查</td><td>33</td></tr><tr><td>2 · semi_analytic</td><td>连续问题的根、全局极小值、有限模态矩阵指数或自相似/行波 ODE</td><td>25</td></tr><tr><td>3 · numerical</td><td>经过网格、时间步及双求解器交叉验证的 PDE 数值参考</td><td>2</td></tr></tbody></table><p>Tier 是构造分类，不是精度等级；与 n64 等网格标签无关。旧 extended 保留 54 个场景，complex 独立提供 60 个。默认 suite 仍为 extended。</p><pre data-lang="PYTHON"><code>from hyperbench import Benchmark\n\nbench = Benchmark(\n    equation="maxwell", suite_name="complex",\n    reference_tiers=["numerical"], grids=[32, 64],\n    solvers=["classic_mc", "wz_llf"],\n)\nprint(bench.scenes)\nbench.prepare("experiments/hyperbolic/my_complex_v001")\n# 冻结并推送代码、协议后：\n# report = Benchmark.load("experiments/hyperbolic/my_complex_v001").run()\n# report.validate()</code></pre><h3>覆盖了哪些复杂情况</h3><p>多尺度与密集间断的输运/Burgers、双向宽频线性波、刚性松弛、移动干湿岸线、强冲击与近真空 Euler Riemann、非线性弹性界面、有限振幅及静止 Alfvén 波、多层反射透射、二维多尺度接触波、严格周期紧支撑涡旋、稳态水力分支与水跃、斜向 KPP 复合波，以及输运与刚性反应耦合的精确接触解；另有绝对值/窗口多频初态、严格真空、干床 Riemann、光滑跨临界流、平面 Noh/Sedov 和两档单步 ZND 行波。</p><h3>如何决定数值参考可用</h3><p>12 个数值候选完成 96 次尝试。两种实现分别接受三档网格与最细网格的 CFL 减半检查；空间差异 ≤0.001，时间差异 ≤0.0002，末次空间收缩比 ≤0.8，双方法差异 ≤0.001。指标是每分量空间 L1 除以 max(RMS,0.1)，再取所有采样时刻/分量的最大值，不是连续误差上界。</p><p>只有变介电系数 Maxwell 与变系数线弹性通过。参考为 N=512、CFL=0.15 的 WENO-Z5 + LLF/阻抗通量 + SSPRK3，经守恒降采样；批准目标网格 N=32/64。未通过的 blast、曲线 Riemann、坝溃、复杂散射、反应热点等不进入 complex suite。</p><h3>GT 是否固定</h3><ul><li>解析/半解析：每个新实验在计时之外生成，场景/网格之间共享；不自动使用全局缓存。</li><li>数值：小型固定 GT bank 随代码保存，读取时校验 SHA-256；不重新推进 PDE。</li><li>报告：使用本次保存的场和参考，只读复核。</li></ul><p>解析/半解析参考一致性在 N=32/64/128 及 10 个输出时刻检查。数值 GT 仅批准 N=32/64。所有场景的最大 horizon 与参数见目录；请求未批准网格会报错。改变物理条件须重新资格验证。</p><div class="note">Noh/Sedov 限于平面 1D，Sedov 从正初始年龄开始；ZND 严格匹配当前单步阈值反应律，需要给定外部边界。并不覆盖多维自相似解、详细化学、3D Maxwell/Mie 或多维弹性模式转换。部分原生 solver 在冷流/真空/干床/反应行波上失败，记录保留。紧支撑涡旋不是截断 Gaussian 涡旋。</div><p>数学依据包括 <a href="https://arxiv.org/abs/1110.0288">SWASHES</a>、<a href="https://www.clawpack.org/riemann_book/html/Nonconvex_scalar.html">非凸 Riemann 解</a>和<a href="https://www.astro.princeton.edu/~jstone/Athena/tests/cp-alfven-wave/cp-alfven.html">有限振幅 Alfvén 波</a>。完整实验协议、失败记录及推导在私有仓库的 COMPLEX_EXTENSION.md 和 v032–v041 归档中。</p>',
  },
];
